config/routes.rb
Rails.application.routes.draw do
  # resources :posts do
  #   get "testajax"
  #   resources :likes
  # end
  get "/posts/new" => "posts#new", :as => :new_post
  post "posts" => "posts#create", :as => :posts
  get "/posts" => "posts#index"
  get "posts/:id/edit" => "posts#edit", :as => :edit_post
  put "posts/:id" => "posts#update", :as => :post
  patch "posts/:id" => "posts#update"
  get "/posts/:id" => "posts#show"
  delete "/posts/:id" => "posts#destroy"
  get "posts/:id/view" => "posts#view"

  get "/posts/:post_id/likes/new" => "likes#new", :as => :new_post_like
  post "posts/:post_id/likes" => "likes#create", :as => :post_likes
  get "posts/:post_id/likes" => "likes#index"
  get "posts/:post_id/likes/:id/edit" => "likes#edit", :as => :edit_post_like
  put "posts/:post_id/likes/:id" => "likes#update", :as => :post_like
  patch "posts/:post_id/likes/:id" => "likes#update"
  get "posts/:post_id/likes/:id" => "likes#show"

   root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :likes
	def self.search(search)
		if search
			post = Post.find_by(name: title)
			if post
				self.where(comment: post)
			else
				Post.all
			end
		else
			Post.all
		end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	# def test_data
	# 	@hello = "Hello mallesh"
 #    end		
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def index
    @post = Post.find(params[:post_id])
    @likes = @post.likes
  end  
  def new
    @post = Post.find(params[:post_id])
    @like = Like.new
  end
  
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(like_params)
    if @like.save
      redirect_to post_likes_path(params[:post_id])
    else
      render :new
    end
  end
  private
  def like_params
    params.require(:like).permit(:description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    if params[:search].present?
     @posts = Post.where("title = ? or comment = ? or count = ?", 
      params[:search], params[:search], params[:search])
    else  
      @posts  = Post.paginate(:page => params[:page], :per_page=>5)
    end

  end
  def show
    @post = Post.find(params[:id])
  end
  def view
    @post = Post.find(params[:id])
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.comment = params[:post][:comment]
    @post.count = params[:post][:count]
    if @post.save 
      redirect_to  posts_path
    else
      render :new
    end
  end
  def edit
    @post = Post.find(params[:id])
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to  posts_path
  end
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end
  def testajax
    
  end

  private
   def post_params
    params.require(:post).permit(:title, :comment, :count)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

   
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_for [@post, @like] do |form| %>
  <p>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <% end %>

app/views/likes/edit.html.erb
<%= render "form" %>

app/views/likes/index.html.erb
<table>
  <thead>
    <style align = "center">
table, th, td {
  border: 1px solid black;
  font-size: 18px;
} 
</style>
<tr>
  <th>Description</th>
</tr>
 <% @likes.each do |t|  %>
 <tr><td><%= t.description %></td>
 <td><%= link_to 'VIEW DETAILS', "/posts/#{t.post.id}/view"%></td></tr>
 <% end %>
  </thead>
</table>
<%= link_to 'BACK',posts_path %>

app/views/likes/new.html.erb
<%= render "form" %>

app/views/likes/show.html.erb
<h1>SHOW</h1>

	<p>
		<%= 'Description' %>
		<%= @like.description %>
	</p>

app/views/likes/view.html.erb
<h1>SHOW</h1>

	<p>
		<%= 'Title' %>
		<%= @post.title %>
	</p>
	<p>
		<%= 'Comment' %>
		<%= @post.comment %>
	</p>
	<p>
		<%= 'Count' %>
		<%= @post.count %>
	</p>

app/views/posts/_form.html.erb
<%= form_for scope: :post, local: true do |form| %>
	<p>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</p>
	<p>
		<%= form.label :comment %>
		<%= form.text_field :comment %>
	</p>
	<p>
		<%= form.label :count %>
		<%= form.text_field :count %>
	</p>
	<p>
		<%= form.submit %>
	</p>
	<% end %>

app/views/posts/edit.html.erb
<h1>EDIT</h1>
<%= form_for @post do |form| %>
	<p>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</p>
	<p>
		<%= form.label :comment %>
		<%= form.text_field :comment %>
	</p>
	<p>
		<%= form.label :count %>
		<%= form.text_field :count %>
	</p>
	<p>
		<%= form.submit %>
	</p>
	<% end %>

app/views/posts/index.html.erb
Enter Title Name : <%= form_tag(posts_path, method: :get) do %>
<%= text_field_tag(:search, params[:title]) %><br><br>
<%= submit_tag ("Search") %><br><br>
<% end %>
<table id="test">
	<thead>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <style align = "center">
table, th, td {
  border: 1px solid black;
  font-size: 18px;
} 
</style>
  <tr>
    
    <th>
    <input type="checkbox" id="qw" name="" value="" >
    </th>
    <th>Sno</th>
    <th>Title</th>
    <th>Comment</th>
    <th>Count</th> 
  </tr>
  <% h = 1 %>
  <% @posts.each do |t|  %>
  <%# @posts.each_with_index  do |t, index| %>
  <tr>
    <td>
    <input type="checkbox" name="" value="" >
    </td>
    <td><%= h %></td>
    <td><%= t.title %></td>
    <td><%= t.comment %></td>
    <td><%= t.count %></td>
    <td><%= link_to 'Edit',edit_post_path(t.id) %></td>
    <td><%= link_to 'Delete',post_path(t.id), method: :delete %></td>
    <td><%= link_to 'Show',post_path(t.id) %></td>
    <td><%= link_to 'Add Like',new_post_like_path(post_id: t.id) %></td>
    <td><%= link_to 'View Likes List',post_likes_path(t.id) %></td>
    <% h +=1 %>
  </tr>

   <% end%>
   
  </thead>
</table>
<%= link_to 'NEW POST',new_post_path %>
<%= will_paginate @posts %><br> 
<!-- <input type="button" id="as" name="checkall" value="CHECK ALL">
<input type="button" id="asd" name="uncheckall" value="UNCHECK ALL"><br><br> -->
<%#= link_to 'CLICK HERE',post_testajax_path(1), :remote => true%>
<script type="text/javascript">
  $(document).ready(function(){
    // $("#as").click(function() {
    //   $('input:checkbox').attr('checked','checked');
    // })

    // $("#asd").click(function() {
    //   $('input:checkbox').removeAttr('checked');
    // })
    
    $("#qw").click(function()  { 
      if($(this).is(':checked')) 
      {
        $('input:checkbox').attr('checked','checked');
      }
      else{
      $('input:checkbox').removeAttr('checked');
      }
    })
    
})
</script>

app/views/posts/new.html.erb
<%= form_for @post do |form| %>
	<p>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</p>
	<p>
		<%= form.label :comment %>
		<%= form.text_field :comment %>
	</p>
	<p>
		<%= form.label :count %>
		<%= form.text_field :count %>
	</p>
	<p>
		<%= form.submit %>
	</p>
	<% end %>

app/views/posts/show.html.erb
<h1>SHOW</h1>

	<p>
		<%= 'Title' %>
		<%= @post.title %>
	</p>
	<p>
		<%= 'Comment' %>
		<%= @post.comment %>
	</p>
	<p>
		<%= 'Count' %>
		<%= @post.count %>
	</p>
	
	

app/views/posts/testajax.js.erb
$(".field").html("Welcome To Sample Works")

app/views/posts/view.html.erb
<h1>SHOW</h1>

	<p>
		<%= 'Title' %>
		<%= @post.title %>
	</p>
	<p>
		<%= 'Comment' %>
		<%= @post.comment %>
	</p>
	<p>
		<%= 'Count' %>
		<%= @post.count %>
	</p>
	
	